// Generated from the shared literature survey workbook.
export const sourceSections = ["Reasoning", "Latent Reasoning", "Taxonmy of Reasoning Models", "Distillation+ Reasoning", "Basic Papers", "Interpretability", "People to Follow"] as const;

export const seedPapers = [
  {
    "title": "What is Reasoning?",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://en.wikipedia.org/wiki/Reason",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Denny Zohu Stanford talk",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "http://youtube.com/watch?v=ebnX5Ur1hBk",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Survey paper-1",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "http://scis.scichina.com/en/2026/161101.pdf",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "LLRM Failures",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://openreview.net/pdf?id=vnX1WHMNmz",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Neuro Symbolic AI",
    "authors": "",
    "year": "2025",
    "section": "Reasoning",
    "venue": "",
    "url": "https://www.ijcai.org/proceedings/2025/1195.pdf",
    "status": "to-read",
    "remarks": "Reasoning",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "From system1 to system 2",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2502.17419",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "From Perception to Cognition: A Survey of Vision-Language Interactive Reasoning in Multimodal Large Language Models",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2509.25373v3",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Survey paper-2",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://dl.acm.org/doi/pdf/10.1145/3729218",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Debating For better Reasoning : EMNLP(2025)",
    "authors": "",
    "year": "2025",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2505.14627",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Reson-RFT (NIPS 2025)",
    "authors": "",
    "year": "2025",
    "section": "Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "(Can be Used as a Compre paper) · Has nice collection of Dataset and Benchmarks in the references.",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Reasoning Models doesn't always say what they think",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2505.05410",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Let's think step by step",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2305.20050",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "LATTE",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "http://arxiv.org/pdf/2412.05479",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Training LLMs to reason in a Continuos Latent space",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Reasoning workshop CVPR",
    "authors": "",
    "year": "2025",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2025/workshop/32288",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "JEPA Papers",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "JEPA + Diffusion + Reasoning is particularly interesting because it naturally extends predictive representation learning to uncertain reasoning trajectories, rather than only uncertain physical futures. That is a conceptually appealing direction, though it is still largely at the stage of open research questions rather than established methods.",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Position Paper",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://openreview.net/pdf?id=BZ5a1r-kVsf",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "JEPA Papers ICLR 2026 Accepted",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://iclr.cc/virtual/2026/papers.html?search=JEPA",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Multimodal Latent Reasoning Via Predective Embeddings ( NIPS 2026 Under Review)",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2604.08065v1",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "ThinkJEPA",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2603.22281",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "(ICLR 2026 Reject)",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2512.19171",
    "status": "to-read",
    "remarks": "JEPA Reasoner",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "(ICLR 2026 Oral)",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2510.00739",
    "status": "to-read",
    "remarks": "JEPA+RL",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "(ICML 2026)",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2603.20111",
    "status": "to-read",
    "remarks": "VarJEPA",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "CVPR (2026)",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "( By keyword search there are 205 papers on reasoning )",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Research resource 29",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/37791",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Let VLM grade their own thoughts",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/36767",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Attention guided perception policy optimization for video reasoning",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/38729",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Research resource 32",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/39212",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Reasoning Transfer from LLMs to VLMs via on-policy Distillation",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/36362",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Research resource 34",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/38068",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Research resource 35",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/36705",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Thinking Diffusion",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/37363",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Machine Unlearning + Reasoning",
    "authors": "",
    "year": "",
    "section": "Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Unlearning in MLLMs",
    "authors": "",
    "year": "2026",
    "section": "Reasoning",
    "venue": "",
    "url": "https://cvpr.thecvf.com/virtual/2026/poster/38833",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Training CoT Via Latent -Variable Inference",
    "authors": "",
    "year": "2023",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2312.02179",
    "status": "to-read",
    "remarks": "NIPS 2023",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Variational Reasoning For LLMs",
    "authors": "",
    "year": "2026",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2509.22637",
    "status": "to-read",
    "remarks": "ICLR 2026",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Latent Visual Reasoning",
    "authors": "",
    "year": "2026",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://openreview.net/pdf?id=j84WR5ORsC",
    "status": "to-read",
    "remarks": "ICLR 2026 · Monday Dissussion (08/10/2026)",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Activation Reasoning",
    "authors": "",
    "year": "2026",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2510.18184",
    "status": "to-read",
    "remarks": "ICLR 2026",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Latent Reasoning Skills for CoT Reasoning",
    "authors": "",
    "year": "2024",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://aclanthology.org/2024.findings-emnlp.206.pdf",
    "status": "to-read",
    "remarks": "ACL findings 2025",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Latent CoT for Visual Reasoning",
    "authors": "",
    "year": "2025",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "NIPS 2025",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Mirage",
    "authors": "",
    "year": "2026",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "CVPR 2026 · Monday Dissussion (08/10/2026)",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Vision Aligned Latent Reasoning for MLLMs",
    "authors": "",
    "year": "",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Latent & Implicit Thinking Workshop",
    "authors": "",
    "year": "",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Let's think Dot by Dot",
    "authors": "",
    "year": "2024",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "COLM 2024",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Think before You Speak : Training LM with Pause Tokens",
    "authors": "",
    "year": "2024",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "ICLR 2024",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Guiding LM Reasoning with Planning Tokens",
    "authors": "",
    "year": "2024",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "COLM 2024",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Disentangling Memory and Reasoning Ability in LLMs",
    "authors": "",
    "year": "2025",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "ACL 2025",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Token Assorted: Mixing Latent and Text Tokens for Improved Language Model Reasoning",
    "authors": "",
    "year": "2025",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "ICML 2025",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Search for more in this",
    "authors": "",
    "year": "",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Latent+Variable+reasoning&btnG=",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "LoopFormer",
    "authors": "",
    "year": "2026",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "ICLR 2026",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Latent Thoughts Tuning",
    "authors": "",
    "year": "2026",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "ICML 2026",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "CoCoMix",
    "authors": "",
    "year": "",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "Must Read",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Mirage:The Illusion of Understanding",
    "authors": "",
    "year": "",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "",
    "status": "to-read",
    "remarks": "Must Read",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Research resource 26",
    "authors": "",
    "year": "",
    "section": "Latent Reasoning",
    "venue": "",
    "url": "https://openaccess.thecvf.com/content/CVPR2026/papers/Li_Latent_Implicit_Visual_Reasoning_CVPR_2026_paper.pdf",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Self Distilled Reasoner",
    "authors": "",
    "year": "2026",
    "section": "Distillation+ Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2601.18734",
    "status": "to-read",
    "remarks": "ICML 2026",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Transfering Reasoning Capabilities to Smaller LLMs using Multi-Teacher KD",
    "authors": "",
    "year": "",
    "section": "Distillation+ Reasoning",
    "venue": "",
    "url": "https://dl.acm.org/doi/pdf/10.1145/3701551.3703577",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Reinforcement Aware KD for LLM reasoning",
    "authors": "",
    "year": "2026",
    "section": "Distillation+ Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2602.22495",
    "status": "to-read",
    "remarks": "ICML 2026 · For Monday meeting",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "On Policy Distillation For LLMs",
    "authors": "",
    "year": "2024",
    "section": "Distillation+ Reasoning",
    "venue": "",
    "url": "https://arxiv.org/pdf/2306.13649",
    "status": "to-read",
    "remarks": "ICLR 2024",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Attention is all you need",
    "authors": "",
    "year": "",
    "section": "Basic Papers",
    "venue": "",
    "url": "https://arxiv.org/abs/1706.03762",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "ViT Paper",
    "authors": "",
    "year": "2010",
    "section": "Basic Papers",
    "venue": "",
    "url": "https://arxiv.org/pdf/2010.11929",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "Visual Instruction Tuning",
    "authors": "",
    "year": "",
    "section": "Basic Papers",
    "venue": "",
    "url": "https://openreview.net/pdf?id=w0H2xGHlkw",
    "status": "to-read",
    "remarks": "(LLaVA--> Large Language and Vision Assistant )",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "VibeThinker -3B",
    "authors": "",
    "year": "",
    "section": "Basic Papers",
    "venue": "",
    "url": "https://arxiv.org/pdf/2606.16140",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "VLMs Survey",
    "authors": "",
    "year": "",
    "section": "Basic Papers",
    "venue": "",
    "url": "https://arxiv.org/pdf/2501.02189",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "B-cos: Alignment is all we need for interpretability",
    "authors": "",
    "year": "",
    "section": "Interpretability",
    "venue": "",
    "url": "https://arxiv.org/abs/2205.10268",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "B-cosification:Transforming Neural Networks to be inherently Interpretable",
    "authors": "",
    "year": "",
    "section": "Interpretability",
    "venue": "",
    "url": "https://arxiv.org/abs/2411.00715",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  },
  {
    "title": "ALOE:: Feature Alignment for Scalable B-cosification of Foundational Vision Transformers",
    "authors": "",
    "year": "",
    "section": "Interpretability",
    "venue": "",
    "url": "https://rmaser.github.io/aloe_project/assets/aloe-cvpr2026.pdf",
    "status": "to-read",
    "remarks": "",
    "keyTakeaways": "",
    "limitations": "",
    "connections": "",
    "tags": "",
    "isRead": 0
  }
] as const;
